In [1]:
print("haha")

haha


In [2]:
import math

In [3]:
r = 3
A = math.pi * r * r
print(A)

28.274333882308138


In [4]:
from math import pi
a = pi * r * r
print(a)

28.274333882308138


In [6]:
print(pi)

3.141592653589793


In [8]:
sqr = math.sqrt(10)
print(sqr)

3.1622776601683795


In [9]:
length = [2,4,6,8]
width = [1.4,3.2,1,6]


In [10]:
length * width

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
length * 2

[2, 4, 6, 8, 2, 4, 6, 8]

In [12]:
import numpy as np

In [13]:
np_length = np.array(length)
print(np_length)

[2 4 6 8]


In [15]:
print(np_length+1)
print(np_length+2)
print(np_length+np_length)


[3 5 7 9]
[ 4  6  8 10]
[ 4  8 12 16]


In [17]:
np_width = np.array(width)
print(np_length)
print(np_width)
print(np_length + np_width)

[2 4 6 8]
[1.4 3.2 1.  6. ]
[ 3.4  7.2  7.  14. ]


In [20]:
print(type(length))
print(type(np_length))

<class 'list'>
<class 'numpy.ndarray'>


In [21]:
baseball_h = np.array([72,78,69,71,76,79])
baseball_w = np.array([180,215,210,188,176,209])

In [32]:
baseball_hm = baseball_h/39.37

In [35]:
BMI = (baseball_w * 0.453592) / (baseball_hm **2)
print(BMI)

[24.41202062 24.8453701  31.01111126 26.22028257 21.42306962 23.54443751]


In [42]:
y = np.array([1,9,3,4,5,6,7,8,2])
my_index = np.array([True, False,True, False,True, False,True, False,True])
print(y[my_index])

[1 3 5 7 2]


In [43]:
y > 5

array([False,  True, False, False, False,  True,  True,  True, False])

In [44]:
print(y>5)

[False  True False False False  True  True  True False]


In [45]:
y5 = y[y>5]
print(y5)

[9 6 7 8]


In [46]:
high = y > 5
print(y[high])

[9 6 7 8]


In [49]:
sub_y = y[[0,4,2]]
print(y)
print(sub_y)

[1 9 3 4 5 6 7 8 2]
[1 5 3]


In [51]:
list_2d = [[72,78,69,71,76,79],[180,215,210,188,176,209]]
np_2d = np.array(list_2d)
print(np_2d)

[[ 72  78  69  71  76  79]
 [180 215 210 188 176 209]]


In [52]:
np_2d.shape

(2, 6)

In [53]:
print(np_2d[0,2])

69


In [54]:
np_2d[0, :]

array([72, 78, 69, 71, 76, 79])

In [55]:
np_2d[1,[0,2,3]]

array([180, 210, 188])

In [56]:
np_2d[:,2:4]

array([[ 69,  71],
       [210, 188]])

In [58]:
from sklearn.datasets import load_iris

In [59]:
iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [65]:
iris_attr = iris.data

species = iris.target
print(iris.feature_names)
print(iris_attr)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3

In [66]:
print(iris_attr.shape)

(150, 4)


In [68]:
print(iris_attr[2,:])

[4.7 3.2 1.3 0.2]


In [82]:
sepal_width = iris_attr[:,1]
print(sepal_width)

[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
 2.6 3.  2.6 2.3 2.7 3.  2.9 2.9 2.5 2.8 3.3 2.7 3.  2.9 3.  3.  2.5 2.9
 2.5 3.6 3.2 2.7 3.  2.5 2.8 3.2 3.  3.8 2.6 2.2 3.2 2.8 2.8 2.7 3.3 3.2
 2.8 3.  2.8 3.  2.8 3.8 2.8 2.8 2.6 3.  3.4 3.1 3.  3.1 3.1 3.1 2.7 3.2
 3.3 3.  2.5 3.  3.4 3. ]


In [83]:
petal_length=iris_attr[94,2]
print(petal_length)

4.2


In [81]:
versicolor = iris_attr[species==1]
print(versicolor)

[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]]


In [85]:
versicolor_mean = np.mean(versicolor[:,2])
print(versicolor_mean)

4.26


In [87]:
def printme(str):
    print(str)
    return

In [88]:
printme("hahahaha")

hahahaha


In [89]:
def printinfo(name, age):
    print("Name: ", name)
    print("Age: ", age)
    return

In [90]:
printinfo("haha", 21)

Name:  haha
Age:  21


In [92]:
printinfo(age=21, name="hahaha")

Name:  hahaha
Age:  21


In [93]:
def add(a,b):
    print(a+b)
    return

In [94]:
add(5,6)

11


In [98]:
def addv(a,b):
    return a+b

In [99]:
catch_v = addv(6,7)
print(catch_v)

13


In [100]:
def fence(str, wrapper):
    return wrapper+str+wrapper

In [101]:
print(fence('name', '*'))

*name*
